apply plugin: "com.android.library"
apply plugin: "kotlin-android"
apply plugin: "kotlin-kapt"

android {
    compileSdkVersion propCompileSdkVersion

    defaultConfig {
        minSdkVersion propMinSdkVersion
        targetSdkVersion propTargetSdkVersion
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            consumerProguardFiles "proguard-rules.pro"
        }
    }

    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
    }
    namespace 'com.dpsoftapps.commons'
}

dependencies {
    // removed external PatternLockView and RtlViewPager dependencies (vendor stubs are provided locally)
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation "androidx.constraintlayout:constraintlayout:2.2.1"
    implementation "androidx.documentfile:documentfile:1.1.0"
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
    implementation "androidx.exifinterface:exifinterface:1.4.2"
    implementation "androidx.biometric:biometric:1.1.0"
    implementation "com.googlecode.ez-vcard:ez-vcard:0.12.2"

    api "joda-time:joda-time:2.14.1"
    api "com.github.tibbi:RecyclerView-FastScroller:5a95285b1f"
    api "com.github.tibbi:reprint:2cb206415d"
    api "androidx.core:core-ktx:1.9.0"
    api "androidx.appcompat:appcompat:1.7.1"
    api "com.google.android.material:material:1.8.0"
    api "com.google.code.gson:gson:2.14.0"

    api "com.github.bumptech.glide:glide:4.14.2"
    kapt "com.github.bumptech.glide:compiler:4.14.2"

    api "androidx.room:room-runtime:2.8.1"
    kapt "androidx.room:room-compiler:2.8.1"
}
